In [35]:
import numpy as np
from numpy import loadtxt
import pandas as pd

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [3]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(a.shape)
print(a.dtype)
print(a.size)

(10,)
int32
10


In [8]:
print(a.sum())

55


In [11]:
b = a*np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print(b)
print(b.sum())

[  1   4   9  16  25  36  49  64  81 100]
385


In [23]:
c = np.random.randint(3,10,size=(4,4))
print(c)


[[3 6 3 8]
 [7 3 7 6]
 [7 9 5 5]
 [9 9 5 5]]


In [36]:
f = np.random.choice([1,2,3,4,5,6,7,8,9,10],size=(4,4))
print(f)

[[ 2  9  4  2]
 [ 4  2  6 10]
 [ 6  6  9  4]
 [ 8  5  3  1]]


In [72]:
arr = np.loadtxt("C:/Users/sogut/Desktop/Test/124.txt",delimiter=",")
print(arr)
arr=arr.astype(int)

[[1. 2. 3.]
 [3. 4. 5.]
 [4. 5. 6.]
 [5. 6. 7.]
 [7. 8. 9.]
 [1. 2. 6.]]


In [90]:
import pandas as pd
import numpy as np

arr = np.arange(1,11).reshape(2,5)
print(arr)

DF = pd.DataFrame(arr)
print(DF)
DF.to_csv('C:/Users/sogut/Desktop/Test/arr1.csv',sep=',')

arr2 = np.arange(0,10,2)
print(arr2)
DF = pd.DataFrame(arr2)
print(DF)
DF.to_csv('C:/Users/sogut/Desktop/Test/arr2.csv',sep=',')



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10
[0 2 4 6 8]
   0
0  0
1  2
2  4
3  6
4  8


In [94]:
import numpy as np
import pandas as pd

a = np.array([[1,6,4],[3,5,7],[8,9,2],[4,3,1]])

rows = ["{},{},{}".format(i,j,k) for i,j,k in a]
print(rows)
text = "\n".join(rows)
print(text)

with open("C:/Users/sogut/Desktop/Test/arr3.csv","w") as f:
    f.write(text)

['1,6,4', '3,5,7', '8,9,2', '4,3,1']
1,6,4
3,5,7
8,9,2
4,3,1


In [104]:
a = np.zeros((3,3))
print("a=\n",a)


a=
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [105]:
b = np.ones((3,3))
print("b=\n",b)

b=
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [106]:
c = np.full((3,3),5)
print("c=\n",c)

c=
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [107]:
d = np.eye(3)
print("d=\n",d)

d=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [109]:
e = np.random.random((3,3))
print("e=\n",e)

e=
 [[0.66612444 0.55238328 0.62221177]
 [0.90859924 0.26518897 0.98837687]
 [0.65299933 0.30216301 0.04529877]]


In [111]:
f = np.random.randint(0,10,(3,3))
print("f=\n",f)

f=
 [[7 7 4]
 [0 1 0]
 [3 8 6]]


In [114]:
g = np.arange(0,10,2)
print("g= ",g)

g=  [0 2 4 6 8]


In [115]:
h = np.linspace(0,10,5)
print("h= ",h)

h=  [ 0.   2.5  5.   7.5 10. ]
